spring.application.name=ProyectoReservas

#Configuración de MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/ProyectoReservas
#spring.datasource.username=alumno
#spring.datasource.password=alumno1
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:postgresql://postgrereservas_user:BlPS3QWoExHqe9pPdqrJ0SDdrFcpLMBv@dpg-d4nvfehr0fns73doaeqg-a/postgrereservas
spring.datasource.username=postgrereservas_user
spring.datasource.password=BlPS3QWoExHqe9pPdqrJ0SDdrFcpLMBv
spring.datasource.driver-class-name=org.postgresql.Driver


# Render requiere conexion SSL
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

# Configuracionn JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Para ver las SQL que se ejecutan
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}